<?php

namespace App\Observers;

use App\Jobs\CheckProxy;
use App\Parser\Finder;
use App\Parser\Proxy;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Support\Facades\DB;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\UriInterface;
use Spatie\Crawler\CrawlObserver;

class PageObserver extends CrawlObserver
{
    //
    /**
     * @inheritDoc
     */
    public function crawled(UriInterface $url, ResponseInterface $response, ?UriInterface $foundOnUrl = null)
    {
        $page        = (string) $response->getBody();
        $proxiesData = Finder::findProxy($page);
        foreach ($proxiesData as $proxyData) {
            array_shift($proxyData);
            $cnt = Proxy::where('ip', DB::raw("inet_aton('{$proxyData[0]}')"))->where('port', $proxyData[1])->count();
            if (!$cnt) {
                CheckProxy::dispatch($proxyData);
            } else {
                echo "{$proxyData[0]}:{$proxyData[1]} already in DB\r\n";
            }
        }
        echo "Crawled: {$url} found ".count($proxiesData)." proxies\r\n";
    }

    /**
     * @inheritDoc
     */
    public function crawlFailed(UriInterface $url, RequestException $requestException, ?UriInterface $foundOnUrl = null)
    {
        echo "Crawl failed: {$url} {$requestException->getMessage()}\r\n";
        // TODO: Implement crawlFailed() method.
    }

    public function willCrawl(UriInterface $url)
    {
        parent::willCrawl($url); // TODO: Change the autogenerated stub
    }

    public function finishedCrawling()
    {
        echo "Crawl finished\r\n";
        parent::finishedCrawling(); // TODO: Change the autogenerated stub
    }
}
